import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TostProvider from "@/components/providers/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <body suppressHydrationWarning={true}>
          <TostProvider />
          {children}
        </body>
      </html>
  );
}
